# Generated by Django 5.2.12 on 2026-03-28 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('code', models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('matrix', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturer', models.CharField(blank=True, max_length=255, null=True)),
                ('lab', models.IntegerField()),
                ('module', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.module')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('day', models.IntegerField()),
                ('shift', models.IntegerField()),
                ('unavailable', models.BooleanField(default=False)),
                ('blocking_modules', models.ManyToManyField(blank=True, null=True, to='scheduler.module')),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.booking')),
            ],
            options={
                'ordering': ['day', 'shift'],
                'unique_together': {('day', 'shift')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_number', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('A', 'Lab Assistant'), ('S', 'Lab Supervisor')], default='A', max_length=2)),
                ('modules', models.ManyToManyField(to='scheduler.module')),
                ('shifts', models.ManyToManyField(to='scheduler.slot')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('shift_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('assistants', models.ManyToManyField(blank=True, null=True, related_name='shift_assistant', to='scheduler.student')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_supervisor', to='scheduler.student')),
            ],
        ),
    ]
