# Generated by Django 5.2.12 on 2026-03-24 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('code', models.CharField(unique=True)),
                ('moduleID', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('matrix', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturer', models.CharField(max_length=255)),
                ('lab', models.IntegerField()),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scheduler.module')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('day', models.IntegerField()),
                ('shift', models.IntegerField()),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scheduler.booking')),
            ],
            options={
                'ordering': ['day', 'shift'],
                'unique_together': {('day', 'shift')},
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_number', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('A', 'Lab Assistant'), ('S', 'Lab Supervisor')], default=1, max_length=2)),
                ('modules', models.ManyToManyField(to='scheduler.module')),
                ('shifts', models.ManyToManyField(to='scheduler.slot')),
            ],
        ),
    ]
