# Generated by Django 5.2.12 on 2026-03-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='assistants',
            field=models.ManyToManyField(related_name='shift_assistant', to='scheduler.student'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='blocking_modules',
            field=models.ManyToManyField(to='scheduler.module'),
        ),
    ]
