# Generated by Django 5.2.12 on 2026-03-24 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_schedule_matrix'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
