# Generated by Django 5.2.12 on 2026-03-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_rename_students_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='lecturer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
