# Generated by Django 5.2.12 on 2026-03-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_alter_booking_lecturer_alter_module_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='unavailable',
            field=models.BooleanField(default=False),
        ),
    ]
