# Generated by Django 5.2.12 on 2026-03-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_slot_unavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='blocking_modules',
            field=models.ManyToManyField(null=True, to='scheduler.module'),
        ),
        migrations.AlterField(
            model_name='student',
            name='modules',
            field=models.ManyToManyField(null=True, to='scheduler.module'),
        ),
        migrations.AlterField(
            model_name='student',
            name='shifts',
            field=models.ManyToManyField(null=True, to='scheduler.slot'),
        ),
    ]
