# Generated by Django 5.2.12 on 2026-03-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_slot_blocking_modules_alter_student_modules_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='blocking_modules',
            field=models.ManyToManyField(to='scheduler.module'),
        ),
        migrations.AlterField(
            model_name='student',
            name='modules',
            field=models.ManyToManyField(to='scheduler.module'),
        ),
        migrations.AlterField(
            model_name='student',
            name='shifts',
            field=models.ManyToManyField(to='scheduler.slot'),
        ),
    ]
