# Generated by Django 5.2.12 on 2026-03-24 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_alter_slot_blocking_modules_alter_student_modules_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='role',
            field=models.CharField(choices=[('A', 'Lab Assistant'), ('S', 'Lab Supervisor')], default='A', max_length=2),
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('shift_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('assistants', models.ManyToManyField(related_name='shift_assistant', to='scheduler.student')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_supervisor', to='scheduler.student')),
            ],
        ),
    ]
