# Generated by Django 5.2.12 on 2026-03-24 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_alter_student_role_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='lecturer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='assistants',
            field=models.ManyToManyField(blank=True, null=True, related_name='shift_assistant', to='scheduler.student'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_supervisor', to='scheduler.student'),
        ),
    ]
