# Generated by Django 5.2.12 on 2026-03-27 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_alter_booking_lecturer_alter_shift_assistants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='module',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.module'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_supervisor', to='scheduler.student'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='blocking_modules',
            field=models.ManyToManyField(blank=True, null=True, to='scheduler.module'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.booking'),
        ),
    ]
